inputs:
  node-version:
    required: true

steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-node@v4
    with:
      node-version: ${{ inputs.node-version }}
      # cache: 'yarn'
  - run: yarn install --frozen-lockfile
