import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { PocketBaseContextProvider } from "../lib/contexts/PocketBaseContext";
import { ChildrenFC } from "../lib/models/ChildrenFC";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: ChildrenFC = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PocketBaseContextProvider>{children}</PocketBaseContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
