import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { PocketBaseContextProvider } from '../contexts/PocketBaseContext'
import type { ChildrenFC } from '../models/ChildrenFC'
// import to trigger `onDevelopmentServerStart`
import '../services/adminPocketBase/adminPocketBase'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout: ChildrenFC = ({ children }) => (
  <html lang="en">
    <body className={inter.className}>
      <PocketBaseContextProvider>{children}</PocketBaseContextProvider>
    </body>
  </html>
)

export default RootLayout
