# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  NODE_ENV: test

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: yarn install
        run: yarn install --frozen-lockfile

  DEBUG:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: pwd/ls
        run: |
          pwd
          ls -la

  tsc:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: yarn tsc
        run: yarn tsc

  format:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: yarn formatCheck
        run: yarn formatCheck

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: yarn lint
        run: yarn lint

  depcruise:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: yarn dc
        run: yarn dc

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: yarn testUnit
        run: yarn testUnit

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: yarn build
        run: |
          cp .env.local.example .env.test
          cat .env.development >> .env.test
          yarn build
